node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"
    
    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "puzzle"
    registryHost = "mindstreamorg/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName

    stage "Build"
    
        sh "/usr/local/bin/docker build -t ${imageName} applications/puzzle"
    
    stage "Push"

        sh "/usr/local/bin/docker push ${imageName}"

    stage "Deploy"
        
        sh "sed 's#mindstreamorg/puzzle:latest#'$BUILDIMG'#' applications/puzzle/k8s/deployment.yaml | /usr/local/bin/kubectl apply -f -"
}
